version: '1.0'

stages:
  - test

steps:

  MyAppDockerImage:
    title: Building Docker Image
    type: build
    image_name: ilancodefresh/json2mysql
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: Dockerfile

  MyUnitTests:
    title: Running Unit tests
    stage: test
    image: ${{MyAppDockerImage}}
    commands:
      - npm run test

  PushToDH:
    type: push
    title: Push Image to Docker Hub
    description: Push Docker Image to Docker Hub Registry
    candidate: ${{MyAppDockerImage}}
    #tag: latest
    #image_name: codefresh/app
    registry: dockerhub
    fail_fast: false
    when:
      branch:
        only:
          - master
    retry:
      maxAttempts: 2
      delay: 5

  Run:
    type: launch-composition
    title: Run app
    description: Free text description
    working_directory: ./
    composition: docker-compose.yml
